import React from 'react';

export const metadata = {
  title: 'Terms of Service | Crack404 Niche Hunter',
  description: 'Terms of Service for Crack404 Niche Hunter.',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-app-bg py-20 px-6">
      <div className="max-w-4xl mx-auto bg-app-surface border border-app-border rounded-2xl p-8 sm:p-12 shadow-2xl relative overflow-hidden">
        {/* Background Glow */}
        <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-accent via-info to-accent opacity-50"></div>
        
        <h1 className="text-3xl sm:text-4xl font-black text-primary-text mb-2">Terms of Service</h1>
        <p className="text-muted-text text-sm mb-10">Last Updated: September 12, 2026</p>

        <div className="space-y-6 text-secondary-text leading-relaxed">
          <p>
            These Terms of Service ("Terms") govern your access to and use of Niche Hunter (https://nichehunter.crack404.com), a service provided by Crack404. By accessing or using our platform, you agree to be bound by these Terms.
          </p>

          <h2 className="text-xl font-bold text-primary-text mt-8 mb-4">1. Description of Service</h2>
          <p>
            Niche Hunter is a market intelligence and telemetry engine that provides automated analysis of search engine results, competitor technical health, and historical trends. The scores and verdicts ("Build", "Avoid", etc.) generated by the platform are algorithmic estimates intended for informational purposes only.
          </p>

          <h2 className="text-xl font-bold text-primary-text mt-8 mb-4">2. Account Registration & Security</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>You must provide a valid email address to authenticate via our One-Time Password (OTP) system.</li>
            <li>You are responsible for maintaining the confidentiality of your account access.</li>
            <li>We reserve the right to suspend or terminate accounts that violate these Terms or abuse our infrastructure.</li>
          </ul>

          <h2 className="text-xl font-bold text-primary-text mt-8 mb-4">3. Acceptable Use Policy</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Use automated bots, scrapers, or scripts to extract data from Niche Hunter.</li>
            <li>Bypass or attempt to bypass any rate limiting, API tracking, or security measures.</li>
            <li>Use the platform for any illegal, harmful, or malicious activities.</li>
          </ul>

          <h2 className="text-xl font-bold text-primary-text mt-8 mb-4">4. Disclaimer of Warranties</h2>
          <p>
            THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. Crack404 makes no warranties, expressed or implied, regarding the absolute accuracy, reliability, or completeness of the telemetry data, competitor audits, or Opportunity Scores. Search engine algorithms change frequently, and our data is a snapshot in time based on third-party API availability.
          </p>

          <h2 className="text-xl font-bold text-primary-text mt-8 mb-4">5. Limitation of Liability</h2>
          <p>
            Crack404 is not a financial or business advisory service. We are not responsible for the success or failure of any software, SaaS, or business venture you choose to build (or not build) based on our data. In no event shall Crack404 be liable for any direct, indirect, incidental, special, or consequential damages, including lost profits or revenue, arising from your use of the platform.
          </p>

          <h2 className="text-xl font-bold text-primary-text mt-8 mb-4">6. Intellectual Property</h2>
          <p>
            All original code, designs, algorithms, and content on the platform are the exclusive property of Crack404. You may not copy, reproduce, or reverse-engineer our platform or its underlying infrastructure.
          </p>

          <h2 className="text-xl font-bold text-primary-text mt-8 mb-4">7. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Continued use of the platform after changes are published constitutes your acceptance of the new Terms.
          </p>

          <h2 className="text-xl font-bold text-primary-text mt-8 mb-4">8. Contact Us</h2>
          <p>
            If you have any questions regarding these Terms, please contact us at contact.support@crack404.com.
          </p>
        </div>
      </div>
    </div>
  );
}